steps:
  # Fetch Admin Panel Release Asset
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-L'
      - '-o'
      - 'admin-panel.tar.gz'
      - 'https://github.com/marcjazz/hublots-marketplace/releases/download/${TAG_NAME}/admin-panel-${TAG_NAME}.tar.gz'

  # Fetch Vendor Panel Release Asset
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-L'
      - '-o'
      - 'vendor-panel.tar.gz'
      - 'https://github.com/marcjazz/hublots-marketplace/releases/download/${TAG_NAME}/vendor-panel-${TAG_NAME}.tar.gz'

  # Extract and Sync Admin Panel to GCS
  - name: 'gcr.io/cloud-builders/gstack'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p admin-dist
        tar -xzf admin-panel.tar.gz -C admin-dist --strip-components=1
        gsutil -m rsync -r -d admin-dist gs://hublots-admin-static
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://hublots-admin-static/**

  # Extract and Sync Vendor Panel to GCS
  - name: 'gcr.io/cloud-builders/gstack'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p vendor-dist
        tar -xzf vendor-panel.tar.gz -C vendor-dist --strip-components=1
        gsutil -m rsync -r -d vendor-dist gs://hublots-vendor-static
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://hublots-vendor-static/**

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TAG_NAME: 'latest' # Default if not provided
